---
- hosts: webservers
  become: true
  
  tasks: 
  - name: Installation of packages on Debian family
    apt: name={{item}} state=present
    when: ansible_os_family == "Debian"
    ignore_errors: true
    with_items:
    - vim
    - zip
    - curl
    - nginx

  - name: Installation of packages on RedHat family
    yum: name={{item}} state=present
    when: ansible_os_family == "RedHat"
    ignore_errors: true
    with_items:
    - vim
    - zip
    - curl
    - nginx
    
